
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:geocoding/geocoding.dart' as geo; // For geocoding
import '../../models/goods_model.dart';
import '../../widgets/custom_button.dart';
import '../../widgets/custom_text_field.dart'; // Assuming you have this

class SellGoodsScreen extends StatefulWidget {
  const SellGoodsScreen({super.key});

  @override
  State<SellGoodsScreen> createState() => _SellGoodsScreenState();
}

class _SellGoodsScreenState extends State<SellGoodsScreen> {
  final _formKey = GlobalKey<FormState>();
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // Form field controllers
  final TextEditingController _productNameController = TextEditingController();
  GoodsCategory _selectedCategory = GOODS_CATEGORIES.first;
  final TextEditingController _priceController = TextEditingController();
  final TextEditingController _quantityController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _pickupAddressController = TextEditingController();
  final TextEditingController _contactController = TextEditingController();
  final TextEditingController _weightController = TextEditingController();

  bool _isLoading = false;

  Future<void> _submitForm() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }
    setState(() => _isLoading = true);

    final User? currentUser = _auth.currentUser;
    if (currentUser == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('You must be logged in to sell goods.')),
      );
      setState(() => _isLoading = false);
      return;
    }

    // Geocode address to lat/lng
    geo.Location? locationCoordinates;
    try {
      List<geo.Location> locations = await geo.locationFromAddress(_pickupAddressController.text.trim());
      if (locations.isNotEmpty) {
        locationCoordinates = locations.first;
      } else {
         ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Could not find coordinates for the address. Please try a more specific address or city.')),
        );
        setState(() => _isLoading = false);
        return;
      }
    } catch (e) {
      print('Geocoding error: $e');
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error getting location: $e. Please check the address.')),
      );
      setState(() => _isLoading = false);
      return;
    }


    final goodsData = Good(
      // productId will be auto-generated by Firestore or set to doc ID later
      productId: '', // Placeholder, will be set to doc ID
      sellerId: currentUser.uid,
      productName: _productNameController.text.trim(),
      category: _selectedCategory,
      price: double.tryParse(_priceController.text.trim()) ?? 0.0,
      quantity: int.tryParse(_quantityController.text.trim()) ?? 0,
      description: _descriptionController.text.trim(),
      location: Location(
        address: _pickupAddressController.text.trim(),
        latitude: locationCoordinates.latitude,
        longitude: locationCoordinates.longitude,
      ),
      contact: _contactController.text.trim(),
      weightKg: double.tryParse(_weightController.text.trim()),
      images: [], // Placeholder for image URLs
      postedAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      isActive: true,
    );

    try {
      DocumentReference docRef = await _firestore.collection('goods').add(goodsData.toJson());
      // Update the goodsData with the actual document ID
      await docRef.update({'productId': docRef.id});

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Goods listed successfully!')),
      );
      _formKey.currentState?.reset();
      // Clear controllers or navigate away
      _productNameController.clear();
      _priceController.clear();
      _quantityController.clear();
      _descriptionController.clear();
      _pickupAddressController.clear();
      _contactController.clear();
      _weightController.clear();
      setState(() {
         _selectedCategory = GOODS_CATEGORIES.first;
      });


    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to list goods: $e')),
      );
    } finally {
      setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        title: const Text('List Your Goods'),
         backgroundColor: theme.colorScheme.primary,
        foregroundColor: theme.colorScheme.onPrimary,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              CustomTextField(
                controller: _productNameController,
                hintText: 'Product Name',
                prefixIcon: Icons.shopping_bag_outlined,
                validator: (value) => value == null || value.isEmpty ? 'Please enter product name' : null,
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<GoodsCategory>(
                value: _selectedCategory,
                decoration: InputDecoration(
                  labelText: 'Category',
                  prefixIcon: Icon(Icons.category_outlined, color: theme.primaryColor),
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                   filled: true,
                ),
                items: GOODS_CATEGORIES.map((GoodsCategory category) {
                  return DropdownMenuItem<GoodsCategory>(
                    value: category,
                    child: Text(category),
                  );
                }).toList(),
                onChanged: (GoodsCategory? newValue) {
                  setState(() {
                    _selectedCategory = newValue!;
                  });
                },
                validator: (value) => value == null ? 'Please select a category' : null,
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: CustomTextField(
                      controller: _priceController,
                      hintText: 'Price (INR)',
                      prefixIcon: Icons.currency_rupee_outlined,
                      keyboardType: TextInputType.number,
                      validator: (value) {
                        if (value == null || value.isEmpty) return 'Please enter price';
                        if (double.tryParse(value) == null || double.parse(value) <= 0) return 'Enter a valid price';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: CustomTextField(
                      controller: _quantityController,
                      hintText: 'Quantity',
                      prefixIcon: Icons.production_quantity_limits_outlined,
                      keyboardType: TextInputType.number,
                       validator: (value) {
                        if (value == null || value.isEmpty) return 'Please enter quantity';
                        if (int.tryParse(value) == null || int.parse(value) <= 0) return 'Enter a valid quantity';
                        return null;
                      },
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
               CustomTextField(
                controller: _weightController,
                hintText: 'Approx. Weight per Unit (kg)',
                prefixIcon: Icons.scale_outlined,
                keyboardType: TextInputType.number,
                validator: (value) {
                  // Optional field, but if provided, validate
                  if (value != null && value.isNotEmpty && (double.tryParse(value) == null || double.parse(value) <= 0)) {
                    return 'Enter a valid positive weight or leave empty';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              CustomTextField(
                controller: _descriptionController,
                hintText: 'Description (size, condition, etc.)',
                prefixIcon: Icons.description_outlined,
                maxLines: 3,
                 validator: (value) => value == null || value.isEmpty ? 'Please enter a description' : null,
              ),
              const SizedBox(height: 16),
              CustomTextField(
                controller: _pickupAddressController,
                hintText: 'Pickup Address / City',
                prefixIcon: Icons.location_on_outlined,
                 validator: (value) => value == null || value.isEmpty ? 'Please enter pickup address' : null,
              ),
              const SizedBox(height: 16),
              CustomTextField(
                controller: _contactController,
                hintText: 'Contact (Phone/Email)',
                prefixIcon: Icons.contact_phone_outlined,
                validator: (value) => value == null || value.isEmpty ? 'Please enter contact info' : null,
              ),
              const SizedBox(height: 24),
              // Image upload placeholder
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  border: Border.all(color: theme.dividerColor),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Column(
                  children: [
                    Icon(Icons.image_outlined, size: 40, color: theme.hintColor),
                    const SizedBox(height: 8),
                    Text('Add Product Images (Coming Soon)', style: TextStyle(color: theme.hintColor)),
                    // Button to pick images would go here
                  ],
                ),
              ),
              const SizedBox(height: 32),
              _isLoading
                  ? const Center(child: CircularProgressIndicator())
                  : CustomButton(
                      text: 'List Goods',
                      onPressed: _submitForm,
                    ),
            ],
          ),
        ),
      ),
    );
  }
}
