// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Replace with your web Firebase config
      return const FirebaseOptions(
        apiKey: 'YOUR_WEB_API_KEY',
        appId: 'YOUR_WEB_APP_ID',
        messagingSenderId: 'YOUR_WEB_MESSAGING_SENDER_ID',
        projectId: 'YOUR_WEB_PROJECT_ID',
        authDomain: 'YOUR_WEB_AUTH_DOMAIN',
        storageBucket: 'YOUR_WEB_STORAGE_BUCKET',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Replace with your Android Firebase config
        return const FirebaseOptions(
          apiKey: 'YOUR_ANDROID_API_KEY',
          appId: 'YOUR_ANDROID_APP_ID',
          messagingSenderId: 'YOUR_ANDROID_MESSAGING_SENDER_ID',
          projectId: 'YOUR_ANDROID_PROJECT_ID',
          storageBucket: 'YOUR_ANDROID_STORAGE_BUCKET',
        );
      case TargetPlatform.iOS:
        // Replace with your iOS Firebase config
        return const FirebaseOptions(
          apiKey: 'YOUR_IOS_API_KEY',
          appId: 'YOUR_IOS_APP_ID',
          messagingSenderId: 'YOUR_IOS_MESSAGING_SENDER_ID',
          projectId: 'YOUR_IOS_PROJECT_ID',
          storageBucket: 'YOUR_IOS_STORAGE_BUCKET',
          iosBundleId: 'YOUR_IOS_BUNDLE_ID',
        );
      case TargetPlatform.macOS:
        // Replace with your macOS Firebase config
         return const FirebaseOptions(
          apiKey: 'YOUR_MACOS_API_KEY',
          appId: 'YOUR_MACOS_APP_ID',
          messagingSenderId: 'YOUR_MACOS_MESSAGING_SENDER_ID',
          projectId: 'YOUR_MACOS_PROJECT_ID',
          storageBucket: 'YOUR_MACOS_STORAGE_BUCKET',
          iosBundleId: 'YOUR_MACOS_BUNDLE_ID', // For macOS, this is often similar to iOS
        );
      case TargetPlatform.windows:
        // Replace with your Windows Firebase config if you have one
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
// IMPORTANT:
// 1. Ensure you have run `flutterfire configure` in your Flutter project root.
// 2. Replace the placeholder values above with your actual Firebase project configuration details.
//    You can find these details in the Firebase console:
//    Project settings > General > Your apps. Select your web, Android, and iOS apps
//    to get their respective configuration objects or files.
